## Multi-node configuration

## Elasticsearch configuration

cluster.name: <elastic_cluster>

cluster.initial_master_nodes:
        - <master_node_1>
        - <master_node_2>
        - <master_node_3>

discovery.seed_hosts:
        - <elasticsearch_ip_node1>
        - <elasticsearch_ip_node2>
        - <elasticsearch_ip_node3>

## Certificates creation
          
# Clients certificates
clients:
  - name: admin
    dn: CN=admin,OU=Docu,O=Wazuh,L=California,C=US
    admin: true
  - name: kibana
    dn: CN=kibana,OU=Docu,O=Wazuh,L=California,C=US    
  - name: filebeat
    dn: CN=filebeat,OU=Docu,O=Wazuh,L=California,C=US


# Kibana-instance
- <kibana_ip>
